//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.24 at 12:31:17 PM EDT 
//


package com.cyres.dataprocessor.cyres.xml.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SegmentDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SegmentDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SegmentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InPointFrameBoundaryStartTC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InPointFrameBoundaryEndTC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OutPointFrameBoundaryStartTC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OutPointFrameBoundaryEndTC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InPointFrameBoundaryStartSecs" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="InPointFrameBoundaryEndSecs" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="OutPointFrameBoundaryStartSecs" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="OutPointFrameBoundaryEndSecs" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SegmentDetail", propOrder = {
    "segmentType",
    "inPointFrameBoundaryStartTC",
    "inPointFrameBoundaryEndTC",
    "outPointFrameBoundaryStartTC",
    "outPointFrameBoundaryEndTC",
    "inPointFrameBoundaryStartSecs",
    "inPointFrameBoundaryEndSecs",
    "outPointFrameBoundaryStartSecs",
    "outPointFrameBoundaryEndSecs"
})
public class SegmentDetail {

    @XmlElement(name = "SegmentType", required = true)
    protected String segmentType;
    @XmlElement(name = "InPointFrameBoundaryStartTC", required = true)
    protected String inPointFrameBoundaryStartTC;
    @XmlElement(name = "InPointFrameBoundaryEndTC", required = true)
    protected String inPointFrameBoundaryEndTC;
    @XmlElement(name = "OutPointFrameBoundaryStartTC", required = true)
    protected String outPointFrameBoundaryStartTC;
    @XmlElement(name = "OutPointFrameBoundaryEndTC", required = true)
    protected String outPointFrameBoundaryEndTC;
    @XmlElement(name = "InPointFrameBoundaryStartSecs")
    protected double inPointFrameBoundaryStartSecs;
    @XmlElement(name = "InPointFrameBoundaryEndSecs")
    protected double inPointFrameBoundaryEndSecs;
    @XmlElement(name = "OutPointFrameBoundaryStartSecs")
    protected double outPointFrameBoundaryStartSecs;
    @XmlElement(name = "OutPointFrameBoundaryEndSecs")
    protected double outPointFrameBoundaryEndSecs;
    @XmlAttribute(name = "id")
    protected Integer id2;

    /**
     * Gets the value of the segmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegmentType() {
        return segmentType;
    }

    /**
     * Sets the value of the segmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegmentType(String value) {
        this.segmentType = value;
    }

    /**
     * Gets the value of the inPointFrameBoundaryStartTC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInPointFrameBoundaryStartTC() {
        return inPointFrameBoundaryStartTC;
    }

    /**
     * Sets the value of the inPointFrameBoundaryStartTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInPointFrameBoundaryStartTC(String value) {
        this.inPointFrameBoundaryStartTC = value;
    }

    /**
     * Gets the value of the inPointFrameBoundaryEndTC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInPointFrameBoundaryEndTC() {
        return inPointFrameBoundaryEndTC;
    }

    /**
     * Sets the value of the inPointFrameBoundaryEndTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInPointFrameBoundaryEndTC(String value) {
        this.inPointFrameBoundaryEndTC = value;
    }

    /**
     * Gets the value of the outPointFrameBoundaryStartTC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutPointFrameBoundaryStartTC() {
        return outPointFrameBoundaryStartTC;
    }

    /**
     * Sets the value of the outPointFrameBoundaryStartTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutPointFrameBoundaryStartTC(String value) {
        this.outPointFrameBoundaryStartTC = value;
    }

    /**
     * Gets the value of the outPointFrameBoundaryEndTC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutPointFrameBoundaryEndTC() {
        return outPointFrameBoundaryEndTC;
    }

    /**
     * Sets the value of the outPointFrameBoundaryEndTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutPointFrameBoundaryEndTC(String value) {
        this.outPointFrameBoundaryEndTC = value;
    }

    /**
     * Gets the value of the inPointFrameBoundaryStartSecs property.
     * 
     */
    public double getInPointFrameBoundaryStartSecs() {
        return inPointFrameBoundaryStartSecs;
    }

    /**
     * Sets the value of the inPointFrameBoundaryStartSecs property.
     * 
     */
    public void setInPointFrameBoundaryStartSecs(double value) {
        this.inPointFrameBoundaryStartSecs = value;
    }

    /**
     * Gets the value of the inPointFrameBoundaryEndSecs property.
     * 
     */
    public double getInPointFrameBoundaryEndSecs() {
        return inPointFrameBoundaryEndSecs;
    }

    /**
     * Sets the value of the inPointFrameBoundaryEndSecs property.
     * 
     */
    public void setInPointFrameBoundaryEndSecs(double value) {
        this.inPointFrameBoundaryEndSecs = value;
    }

    /**
     * Gets the value of the outPointFrameBoundaryStartSecs property.
     * 
     */
    public double getOutPointFrameBoundaryStartSecs() {
        return outPointFrameBoundaryStartSecs;
    }

    /**
     * Sets the value of the outPointFrameBoundaryStartSecs property.
     * 
     */
    public void setOutPointFrameBoundaryStartSecs(double value) {
        this.outPointFrameBoundaryStartSecs = value;
    }

    /**
     * Gets the value of the outPointFrameBoundaryEndSecs property.
     * 
     */
    public double getOutPointFrameBoundaryEndSecs() {
        return outPointFrameBoundaryEndSecs;
    }

    /**
     * Sets the value of the outPointFrameBoundaryEndSecs property.
     * 
     */
    public void setOutPointFrameBoundaryEndSecs(double value) {
        this.outPointFrameBoundaryEndSecs = value;
    }

    /**
     * Gets the value of the id2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId2() {
        return id2;
    }

    /**
     * Sets the value of the id2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId2(Integer value) {
        this.id2 = value;
    }

	@Override
	public String toString() {
		return "SegmentDetail [segmentType=" + segmentType + ", inPointFrameBoundaryStartTC="
				+ inPointFrameBoundaryStartTC + ", inPointFrameBoundaryEndTC=" + inPointFrameBoundaryEndTC
				+ ", outPointFrameBoundaryStartTC=" + outPointFrameBoundaryStartTC + ", outPointFrameBoundaryEndTC="
				+ outPointFrameBoundaryEndTC + ", inPointFrameBoundaryStartSecs=" + inPointFrameBoundaryStartSecs
				+ ", inPointFrameBoundaryEndSecs=" + inPointFrameBoundaryEndSecs + ", outPointFrameBoundaryStartSecs="
				+ outPointFrameBoundaryStartSecs + ", outPointFrameBoundaryEndSecs=" + outPointFrameBoundaryEndSecs
				+ ", id2=" + id2 + "]";
	}

}