//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.24 at 12:31:17 PM EDT 
//


package com.cyres.dataprocessor.xml.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AssetInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssetInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Genre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TotalSegments" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TotalAdSegments" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TotalProgramSegments" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AudioVolume" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AudioPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AudioFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ControlPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ResultsPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WorkAudioPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProcessStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ProcessStartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProcessEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ProcessEndTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssetInformation", propOrder = {
    "name",
    "id",
    "genre",
    "totalSegments",
    "totalAdSegments",
    "totalProgramSegments",
    "audioVolume",
    "audioPath",
    "audioFile",
    "controlPath",
    "resultsPath",
    "workAudioPath",
    "processStartDate",
    "processStartTime",
    "processEndDate",
    "processEndTime"
})
public class AssetInformation {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "ID")
    protected int id;
    @XmlElement(name = "Genre", required = true)
    protected String genre;
    @XmlElement(name = "TotalSegments")
    protected int totalSegments;
    @XmlElement(name = "TotalAdSegments")
    protected int totalAdSegments;
    @XmlElement(name = "TotalProgramSegments")
    protected int totalProgramSegments;
    @XmlElement(name = "AudioVolume", required = true)
    protected String audioVolume;
    @XmlElement(name = "AudioPath", required = true)
    protected String audioPath;
    @XmlElement(name = "AudioFile", required = true)
    protected String audioFile;
    @XmlElement(name = "ControlPath", required = true)
    protected String controlPath;
    @XmlElement(name = "ResultsPath", required = true)
    protected String resultsPath;
    @XmlElement(name = "WorkAudioPath", required = true)
    protected String workAudioPath;
    @XmlElement(name = "ProcessStartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar processStartDate;
    @XmlElement(name = "ProcessStartTime", required = true)
    protected String processStartTime;
    @XmlElement(name = "ProcessEndDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar processEndDate;
    @XmlElement(name = "ProcessEndTime", required = true)
    protected String processEndTime;
    @XmlAttribute(name = "id")
    protected Integer id2;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setID(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the genre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenre() {
        return genre;
    }

    /**
     * Sets the value of the genre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenre(String value) {
        this.genre = value;
    }

    /**
     * Gets the value of the totalSegments property.
     * 
     */
    public int getTotalSegments() {
        return totalSegments;
    }

    /**
     * Sets the value of the totalSegments property.
     * 
     */
    public void setTotalSegments(int value) {
        this.totalSegments = value;
    }

    /**
     * Gets the value of the totalAdSegments property.
     * 
     */
    public int getTotalAdSegments() {
        return totalAdSegments;
    }

    /**
     * Sets the value of the totalAdSegments property.
     * 
     */
    public void setTotalAdSegments(int value) {
        this.totalAdSegments = value;
    }

    /**
     * Gets the value of the totalProgramSegments property.
     * 
     */
    public int getTotalProgramSegments() {
        return totalProgramSegments;
    }

    /**
     * Sets the value of the totalProgramSegments property.
     * 
     */
    public void setTotalProgramSegments(int value) {
        this.totalProgramSegments = value;
    }

    /**
     * Gets the value of the audioVolume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudioVolume() {
        return audioVolume;
    }

    /**
     * Sets the value of the audioVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudioVolume(String value) {
        this.audioVolume = value;
    }

    /**
     * Gets the value of the audioPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudioPath() {
        return audioPath;
    }

    /**
     * Sets the value of the audioPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudioPath(String value) {
        this.audioPath = value;
    }

    /**
     * Gets the value of the audioFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudioFile() {
        return audioFile;
    }

    /**
     * Sets the value of the audioFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudioFile(String value) {
        this.audioFile = value;
    }

    /**
     * Gets the value of the controlPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlPath() {
        return controlPath;
    }

    /**
     * Sets the value of the controlPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlPath(String value) {
        this.controlPath = value;
    }

    /**
     * Gets the value of the resultsPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultsPath() {
        return resultsPath;
    }

    /**
     * Sets the value of the resultsPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultsPath(String value) {
        this.resultsPath = value;
    }

    /**
     * Gets the value of the workAudioPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkAudioPath() {
        return workAudioPath;
    }

    /**
     * Sets the value of the workAudioPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkAudioPath(String value) {
        this.workAudioPath = value;
    }

    /**
     * Gets the value of the processStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProcessStartDate() {
        return processStartDate;
    }

    /**
     * Sets the value of the processStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProcessStartDate(XMLGregorianCalendar value) {
        this.processStartDate = value;
    }

    /**
     * Gets the value of the processStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessStartTime() {
        return processStartTime;
    }

    /**
     * Sets the value of the processStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessStartTime(String value) {
        this.processStartTime = value;
    }

    /**
     * Gets the value of the processEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProcessEndDate() {
        return processEndDate;
    }

    /**
     * Sets the value of the processEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProcessEndDate(XMLGregorianCalendar value) {
        this.processEndDate = value;
    }

    /**
     * Gets the value of the processEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessEndTime() {
        return processEndTime;
    }

    /**
     * Sets the value of the processEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessEndTime(String value) {
        this.processEndTime = value;
    }

    /**
     * Gets the value of the id2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId2() {
        return id2;
    }

    /**
     * Sets the value of the id2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId2(Integer value) {
        this.id2 = value;
    }

}
