//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.24 at 12:31:17 PM EDT 
//


package com.cyres.dataprocessor.xml.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SegmentSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SegmentSummary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SegmentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InPointTC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OutPointTC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InPointSecs" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="OutPointSecs" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SegmentSummary", propOrder = {
    "segmentType",
    "inPointTC",
    "outPointTC",
    "inPointSecs",
    "outPointSecs"
})
public class SegmentSummary {

    @XmlElement(name = "SegmentType", required = true)
    protected String segmentType;
    @XmlElement(name = "InPointTC", required = true)
    protected String inPointTC;
    @XmlElement(name = "OutPointTC", required = true)
    protected String outPointTC;
    @XmlElement(name = "InPointSecs")
    protected double inPointSecs;
    @XmlElement(name = "OutPointSecs")
    protected double outPointSecs;
    @XmlAttribute(name = "id")
    protected Integer id2;

    /**
     * Gets the value of the segmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegmentType() {
        return segmentType;
    }

    /**
     * Sets the value of the segmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegmentType(String value) {
        this.segmentType = value;
    }

    /**
     * Gets the value of the inPointTC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInPointTC() {
        return inPointTC;
    }

    /**
     * Sets the value of the inPointTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInPointTC(String value) {
        this.inPointTC = value;
    }

    /**
     * Gets the value of the outPointTC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutPointTC() {
        return outPointTC;
    }

    /**
     * Sets the value of the outPointTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutPointTC(String value) {
        this.outPointTC = value;
    }

    /**
     * Gets the value of the inPointSecs property.
     * 
     */
    public double getInPointSecs() {
        return inPointSecs;
    }

    /**
     * Sets the value of the inPointSecs property.
     * 
     */
    public void setInPointSecs(double value) {
        this.inPointSecs = value;
    }

    /**
     * Gets the value of the outPointSecs property.
     * 
     */
    public double getOutPointSecs() {
        return outPointSecs;
    }

    /**
     * Sets the value of the outPointSecs property.
     * 
     */
    public void setOutPointSecs(double value) {
        this.outPointSecs = value;
    }

    /**
     * Gets the value of the id2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId2() {
        return id2;
    }

    /**
     * Sets the value of the id2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId2(Integer value) {
        this.id2 = value;
    }

	@Override
	public String toString() {
		return "SegmentSummary [segmentType=" + segmentType + ", inPointTC=" + inPointTC + ", outPointTC=" + outPointTC
				+ ", inPointSecs=" + inPointSecs + ", outPointSecs=" + outPointSecs + ", id2=" + id2 + "]";
	}

}
